### ISSUE TITLE
program run error

### ISSUE THREAD

**Issue by dreaming0017** [angr/acsac-course#2]
Hello,I found a program that can't run correctly with the latest angr. The error is at line 23 in acsac-course/exercises/slide_110/vuln.solution.py .The consle shows that "unsafe_constraints = [ path.state.se.Or(saved_eip < project.loader.min_addr(), saved_eip > project.loader.max_addr()) ]
TypeError: 'int' object is not callable".Could you help me? I'm looking forward your reply.

**Comment by rhelmot** [comment]
min_addr and max_addr are properties now instead of functions! We just need
to remove the function call.

**Comment by dreaming0017** [comment]
I see，thank you very much.
