### ISSUE TITLE
Update "CFGAccurate" to "CFGEmulated"

### ISSUE THREAD

**Issue by 0x4C43** [angr/acsac-course#3]
“CFGAccurate” has deprecated in angr8.
1. https://github.com/angr/acsac-course/blob/9c7d5fd480ab221395618be9a5e9c1e35cabbf0d/exercises/slide_70-75/0.solution.py#L14

2. https://github.com/angr/acsac-course/blob/9c7d5fd480ab221395618be9a5e9c1e35cabbf0d/exercises/slide_91-94/0.solution.py#L30

**Comment by rhelmot** [comment]
Can you do this as a pull request please
